bounswe/bounswe2023group7

- .github/workflows/frontend-deploy.yml
We added frontend-deploy.yml file for the actions pipeline as we indicated in #273 . The code needs to be reviewed.
> #273 Created Actions Pipeline for Frontend

- ludos/frontend/src/App.js
- ludos/frontend/src/components/sidebar.js
- ludos/frontend/src/layout.js
- ludos/frontend/src/pages/landingPage.js
I changed the layout structure for our application and introduced a background color for improved visual appeal. It resolves the issue where the background color is not visible in the application.
**Changes**:
- **Layout Structure**: The structure of the layout has been restructured for better organization and readability.
- **Background Color**: I've added a background color with code #0C1929 to give the application a cohesive and visually appealing look.
- **Mock Landing Page**: For testing purposes, I've included a mock landing page. This allows us to validate that the layout changes do not interfere with the content.
> Layout structure changed

- ludos/mobile/lib/activation_for_password_reset.dart
- ludos/mobile/lib/forgot_password.dart
- ludos/mobile/lib/login_page.dart
- ludos/mobile/lib/pages/taslak.dart
- ludos/mobile/lib/reset_password.dart
- ludos/mobile/pubspec.lock
- ludos/mobile/pubspec.yaml
I implemented most of the structures for forgot password operation. After backend team provide the endpoint I will finalize the operation. For now, review is needed before merge.
> #312 forgot password pages

- ludos/mobile/lib/login_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/sign_up_page.dart
- ludos/mobile/lib/userProvider.dart
- ludos/mobile/pubspec.lock
- ludos/mobile/pubspec.yaml
I implemented a sidebar which contains the username and the log out button is user is logged in; the log in button is the user is not logged in yet.
> #356 implemented sidebar in home page

- ludos/frontend/src/pages/LoginPage.js
- ludos/frontend/src/pages/SignupPage.js
I fixed rerendering issue just by changing one line. This was a little bug. It can be quickly merged.
> I fixed rerendering

- ludos/frontend/README.md
I updated readme for milestone 1 and explained docker build instructions. Additional changes may be done.
> Updated readme for milestone 1

- ludos/README.md
I created the README.md file for all of the project.
> Create README.md for all of the project

- ludos/mobile/lib/change_password.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/login_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/sign_up_page.dart
- ludos/mobile/lib/userProvider.dart
#420 I added change password API service and to be able to send request, I needed the token of the user. So, I also changed the login API service and user provider files.
> feature: change password

- ludos/backend/src/controllers/user.controller.ts
- ludos/backend/src/dtos/user/request/edit-info.dto.ts
- ludos/backend/src/services/user.service.ts
Added edit-user-info endpoint.
This closes #432
> edit user info endpoint

- ludos/mobile/lib/create_game.dart
- ludos/mobile/lib/create_game_second.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/login_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/game_summary.dart
#467 The game page is converted to generic type. When the game is selected in the games page, the game page is loaded the information of that game. Some styling and pixel overflows will be handled after team meeting.
> feature: game page

- ludos/mobile/lib/create_game.dart
- ludos/mobile/lib/create_game_second.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/game_summary.dart
I added necessary mechanism to follow/unfollow a game, also connected mechanism to Backend API endpoints. Review is needed.
> #424 follow/unfollow game endpoint connection

- ludos/mobile/lib/create_game.dart
- ludos/mobile/lib/create_game_second.dart
- ludos/mobile/lib/games_page.dart
I put the create game button at the top of the page for easy access. And changed it to Icon Button with "+".
> Changed the create game button in games page

- ludos/backend/src/controllers/user.controller.ts
- ludos/backend/src/services/user.service.ts
> creating get user info by id

- ludos/backend/src/controllers/game.controller.ts
- ludos/backend/src/dtos/game/request/edit.dto.ts
- ludos/backend/src/services/game.service.ts
> add edit game by id endpoint

- ludos/frontend/src/pages/CreateThreadPage.js
- ludos/frontend/src/pages/ForumsPage.js
- ludos/frontend/src/pages/LoginPage.js
As mentioned in the #555 , I added the "Create- a thread" button to the Forums Page.
- I added a section that contains the button, I added a text to draw attention from users.
- The button navigates to the login page if the user is not logged in; and navigates to the create thread page if the user is logged in.
- When navigating to pages, I realized that the page is not scrolled to top; so I added `useEffect` to scroll to the top by default. 
#555
> Added a section to Forums Page for creating thread

- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/main.dart
Changes made were summarized under the comment section of the [issue](https://github.com/bounswe/bounswe2023group7/issues/529).
> #529 Updated visibility of both games page and create games pages to unlogged user.

- ludos/backend/src/controllers/review.controller.ts
- ludos/backend/src/dtos/review/response/getInfo.dto.ts
- ludos/backend/src/services/review.service.ts
revised of the revew flows, GetReviewById and GetReviewsByGameId endpoints, plus ReviewGetInfoResponseDto
> revision of review get review by id and by game id flows

- ludos/frontend/src/components/GroupTopic.js
- ludos/frontend/src/components/TrendingGamesSlider.js
- ludos/frontend/src/pages/Homepage.js
I changed the library issue because that causes problems in docker.
> Changed material ui to mui

- ludos/mobile/lib/create_thread_page.dart
- ludos/mobile/lib/forum_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/reusable_widgets/forum_comment.dart
- ludos/mobile/lib/reusable_widgets/forum_thread.dart
- ludos/mobile/lib/thread_page.dart
Issue Number #570 
I have added a comment feature to the app. I have created :
* ludos/mobile/lib/reusable_widgets/forum_comment.dart to use a comment in proper format.
For the PR, like/dislike functions are missing. It will be completed with forum like/dislike.
> Added Comments to the Forum

- ludos/mobile/lib/create_game.dart
- ludos/mobile/lib/create_game_second.dart
I have changed age, tag and platform field options in create game pages according to the [this issue](https://github.com/bounswe/bounswe2023group7/issues/513).
> Changed age, tag, platform fields of create game page

- ludos/frontend/src/components/CreateGameForum.js
- ludos/frontend/src/components/ThreadComponent.js
- ludos/frontend/src/components/sidebar.js
- ludos/frontend/src/pages/Homepage.js
- ludos/frontend/src/pages/ThreadPage.js
I added the tags & platforms section as we discussed how we should proceed with the mobile team. Right now, they are synced. I also made some enhancements to sidebar and thread component.
- Expanded the list of the predefined tags & platforms
- Comment text should not be empty check is added
- Non registered users redirected to sign up page if attempted to comment functionality is added
- Image section is added to thread components
- Game name is fixed in home page
- Create Game button navigates to signup page if user is not logged in check is added.
#513 , #514
> Arranged tags/platforms & enhanced components

- ludos/frontend/src/App.js
- ludos/frontend/src/pages/ProfilePage.js
In this branch:
* The profile router is added to app.js. With using profile id, you can reach different profiles.
* Profile visibilities adjusted. User can visit his/her profile page with using his/her profile id. Thus, whenever he/she sees himself/herself in reviews, forum can reach profile page and edit their information.
*  Photos can be seen now.
*  While editing profile information, in modal fields the information is loaded to fields.
*  The game limit is increased to 10.
> profile page distinction, page revision

- ludos/mobile/lib/edit_game.dart
- ludos/mobile/lib/edit_game_second.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/helper/APIService.dart
I have created edit game pages. You can access it from the drawer of a game page. All the fields are decided in [this issue](https://github.com/bounswe/bounswe2023group7/issues/513)
> Edit game pages

- ludos/mobile/lib/forum_page.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/home_game_sum.dart
- ludos/mobile/lib/thread_page.dart
Reorganized the home page and placed buttomNavigationBar on the necessary pages.
I have created a homeGameSum widget to use on the home page.
> Reorganized the Home Page

- ludos/mobile/lib/forum_page.dart
- ludos/mobile/lib/helper/APIService.dart
I added simple search functionality to the forum.
It allows you to search by a key in the title and the content of a thread.
> Added Search to the Forum

- ludos/mobile/android/app/src/main/AndroidManifest.xml
I have changed the app name displayed on the Android screen.
> Changed the App Name

- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/reusable_widgets/game_summary.dart
- ludos/mobile/lib/reusable_widgets/home_game_sum.dart
The average rating in home page and in games page is changed. The game story in Games page changed from default string to the real one.
> Changed the average rating and game story

- ludos/mobile/lib/create_entity.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/helper/EntityContent.dart
I have implemented the create entity page. You can access it from the drawer of the game page. You can successfully create an entity, it it seen in the database. But the "See entities" page is not implemented yet.
> Create Entity page is implemented

- ludos/frontend/src/components/ForumTopicForGame.js
- ludos/frontend/src/components/Review.js
> bugfix for link

- ludos/README.md
- ludos/mobile/README.md
Updated README.md of Ludos with the new .apk link.
Updated README.md of mobile folder.
> Update README.md with the new .apk Link

- ludos/frontend/src/components/ForumTopic.js
- ludos/frontend/src/components/ForumTopicForGame.js
> bugfixed for other link

- ludos/README.md
> Version Update README.md

- ludos/frontend/src/App.js
- ludos/frontend/src/pages/EntityPage.js
I designed the entity page of games.
* User can see the features of entities.
* Image and information is connected to backend.
* Story and bio part is mock data.
entity/8045be24-7452-4f04-8365-eedaa7965afb with using this path you can see compitable entity page with mock data. Otherwise, you can see Nina Williams's bio and story with other entities. 
Story and bio should be required. We can discuss about it.
> entity page is structured

- ludos/mobile/lib/forum_page.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/game_reviews_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/custom_navigation_bar.dart
- ludos/mobile/lib/search_game.dart
- ludos/mobile/lib/search_page.dart
- ludos/mobile/lib/thread_page.dart
As I mentioned in the[ issue](https://github.com/bounswe/bounswe2023group7/issues/664), I created a custom navigation bar for efficiency. Review is needed to test bar's functionality.
> #664 created customized bottom navigation bar

- ludos/mobile/lib/activation_for_password_reset.dart
- ludos/mobile/lib/create_entity.dart
- ludos/mobile/lib/create_game_second.dart
- ludos/mobile/lib/create_thread_page.dart
- ludos/mobile/lib/edit_game_second.dart
- ludos/mobile/lib/forgot_password.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/custom_widgets.dart
- ludos/mobile/lib/reusable_widgets/forum_comment.dart
- ludos/mobile/lib/reusable_widgets/forum_thread.dart
- ludos/mobile/lib/reusable_widgets/need_login_message.dart
- ludos/mobile/lib/search_game.dart
- ludos/mobile/lib/thread_page.dart
Issue: #648 
Description: 
In the mobile folder, there were repeating snackbars where the login is needed and a response is not okay. 
I moved these snackbars to a new file and called them when they are needed. 
Test:
We need to be sure these snackbars are showing when they are necessary.
> Refactoring SnackBars

- ludos/mobile/lib/create_entity.dart
- ludos/mobile/lib/helper/APIService.dart
Entity properties section added to create entity page after the discussion with the frontend team.
> Entity properties section

- ludos/mobile/lib/entities_page.dart
- ludos/mobile/lib/entity_page.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/reusable_widgets/entity_summary.dart
You can see the entities categorized in the drawer of Game page. I welcome any feedback and suggestions. Feel free to share your thoughts on the design.
> Entities and Entity page

- ludos/mobile/lib/edit_thread_page.dart
- ludos/mobile/lib/forum_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/reusable_widgets/custom_widgets.dart
- ludos/mobile/lib/reusable_widgets/forum_comment.dart
- ludos/mobile/lib/thread_page.dart
Issue: #647 
Description: 
I added the edit and delete features for the threads and comments.
> Edit/Delete for Thread and Comment

- ludos/backend/src/dtos/comment/response/get-comment.response.dto.ts
- ludos/backend/src/services/comment.service.ts
I added isLiked and isDisliked fields to the get comment response.
They return true/false indicating whether the user who used the endpoint liked or disliked the comment.
> get comment response has isliked isdisliked fields for the user

- ludos/frontend/.eslintrc.js
- ludos/frontend/src/App.js
- ludos/frontend/src/components/CommentComponent.js
- ludos/frontend/src/components/EditThreadForm.js
- ludos/frontend/src/components/ThreadComponent.js
- ludos/frontend/src/pages/EditThreadPage.js
- ludos/frontend/src/pages/ThreadPage.js
I implemented like, dislike, edit, delete threads and like, dislike, edit, delete comments and also fixed the issue about images that are not seen on the thread.
- Implemented like, dislike, edit, and delete threads. Only the owner of the user can delete and update their thread. When user double likes/dislikes, it takes their likes/dislike back. When a user likes when they are already disliked, the dislike is taken back, and the like is given, and vice versa.
- Implemented like, dislike, edit, and delete comments. The same logic for deleting/updating/liking/disliking the comments is valid.
- The images uploaded while creating the thread were not seen on the thread component. This was because images are seen as JSON, I fixed the problem by parsing it.
- The threads and comments were using …
> Feature/fe/654 655/like dislike delete update thread comment

- ludos/frontend/src/components/ForumTopic.js
- ludos/frontend/src/pages/ForumsPage.js
- ludos/frontend/src/pages/ThreadPage.js
I connected to backend the latest topics section on the forums page. Also, I made the owner username and game name on the thread page clickable.
- Latest topic component is connected to the backend so that the last 3 threads opened are seen on the forums page.
- On the thread page, when clicking on the username who opened the thread; it navigates to the user's profile page.
- Similarly, when clicking on the game name of the thread; it navigates to the game's page.
The last 2 changes were not requested but I noticed them while testing, and completed them to enhance the user experience of our platform.
#656
> Feature/fe/473 475/forums page sidebar

- ludos/mobile/lib/helper/colors.dart
- ludos/mobile/lib/reusable_widgets/custom_navigation_bar.dart
- ludos/mobile/lib/search_page.dart
- ludos/mobile/lib/search_page_game.dart
#667 implemented games part for the search page in mobile app
> Games part in the mobile search page

- ludos/mobile/lib/entity_page.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/game_reviews_page.dart
- ludos/mobile/lib/thread_page.dart
I made the texts in pages:
- Game Page
- Entity Page
- Thread Page
- Review Page
selectable and added a Annotation button for future use. You can try it in your emulator by long press.
> Selectable text and annotation button

- ludos/frontend/src/components/GameCard.js
- ludos/frontend/src/components/RelatedGamesTab.js
- ludos/frontend/src/pages/GamePage.js
- ludos/frontend/src/pages/GamesPage.js
I created the game topic component and used this component in Games Page and Related Games tab in Game Page. For detailed information you can visit issue [#702](https://github.com/bounswe/bounswe2023group7/issues/702)
> Refactor GamePage and RelatedGamesTab components

- ludos/mobile/lib/main.dart
- ludos/mobile/pubspec.lock
Profile photo for unsigned user bug is fixed.
> Drawer Photo Bug

- ludos/mobile/lib/detailed_game_search.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/custom_navigation_bar.dart
- ludos/mobile/lib/search_landing_page.dart
- ludos/mobile/lib/search_page.dart
- ludos/mobile/lib/search_page_game.dart
I implemented detailed game search mechanism. Functionality should be reviewed from 'favorite' icon on the bottomNavigationBar.
> #690 detailed game search implemented.

- ludos/frontend/src/components/CreateThreadForm.js
- ludos/frontend/src/components/Header.js
I replaced the search bar with no functionality with an autocomplete search bar. Users can search three things:
- Users
- Games
- Forum Threads
I added icons to the options of the autocomplete so that user can easily distinguish different type options from each other
> Refactor search functionality and add autocomplete feature

- ludos/frontend/src/components/EntityTab.js
- ludos/frontend/src/pages/EntityPage.js
- ludos/frontend/src/pages/GamePage.js
What is modified:
* Entity tab has the entities of the game.
* Add entity button added on game page.
* Entity page revised. Features are grouped based on their length. Long features are on the right and short features are below photo.
> added entitites to game page and entity page revised

- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/rec_games.dart
- ludos/mobile/lib/user_profile_page.dart
Added recommended games for users profile page. #703
> Recommended Games for User

- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/reusable_widgets/rec_games.dart
Added recommended games at game page. #701
> Recommended Games at Game Page

- ludos/mobile/lib/user_profile_page.dart
I added an information box in the profile page. If you click on the mail address, you will be directed to the mail application of your android device.
> Info box for applying for different user types

- ludos/frontend/src/components/CreateThreadForm.js
I added these features:
- Now user can see the image she uploaded.
- Users can remove the image they uploaded.
These are fundamental features but I couldn't do these while implementing create thread page. It looks like this:
> Add image preview and remove functionality in CreateThreadForm.js

- ludos/frontend/src/components/CreateEntityForm.js
- ludos/frontend/src/pages/EntityPage.js
I change default properties' keys:
- "Image Link" ---> "image"
- "Description" ---> "description"
Now it will be easier to display images and descriptions on both mobile and web
> Updated default property names in CreateEntityForm.js

- ludos/mobile/lib/detailed_post_search.dart
- ludos/mobile/lib/detailed_user_search.dart
- ludos/mobile/lib/reusable_widgets/custom_navigation_bar.dart
- ludos/mobile/lib/search_landing_page.dart
I merged user search into main search page. Also, I changed root for reaching main search page. Now, it can be accessed via search icon from bottom navigation bar as it should be. Review is needed.
> #744 merged users search into main search page - mobile app

- ludos/mobile/lib/reusable_widgets/game_summary.dart
I attempted to resolve image scale problem by converting clipboard image to background image. Review is needed. Further design ideas can be implemented later.
> #689 image scale problem for games resolved in the mobile app.

- ludos/annotation/src/controllers/annotation.controller.ts
- ludos/annotation/src/repositories/annotation.repository.ts
- ludos/annotation/src/services/annotation.service.ts
- ludos/backend/src/controllers/annotation.controller.ts
- ludos/backend/src/services/annotation.service.ts
delete annotation by id is created.
> Delete annotation by id

- ludos/frontend/src/components/Header.js
I added group search feature to the header.
> Refactor Header component to include group navigation

- ludos/frontend/src/components/CreateEntityForm.js
- ludos/frontend/src/pages/EntityPage.js
I implemented annotation features in entity page. Now users can add and see annotations on description section of the entity page. I also fixed small bugs in both entiy page and create entity page. Detailed information can be seen in [#794](https://github.com/bounswe/bounswe2023group7/issues/794)
> annotation is added and entity page is revised

- ludos/annotation/src/controllers/annotation.controller.ts
- ludos/annotation/src/repositories/annotation.repository.ts
- ludos/annotation/src/services/annotation.service.ts
- ludos/backend/src/controllers/annotation.controller.ts
- ludos/backend/src/services/annotation.service.ts
ı created comment annotation endpoint.
> comment annotation created

- ludos/mobile/lib/main.dart
The notification button is non-functional, we removed the icon.
> remove notifications button

- ludos/frontend/src/pages/GamePage.js
I connected the delete annotation API to the game bio annotations. Now, deleting action will take place in the database as well.
> added delete gamebio annotation

- ludos/frontend/src/components/DescriptionTab.js
- ludos/frontend/src/components/RelatedGamesTab.js
- ludos/frontend/src/pages/GamePage.js
I added annotation feature to game trivia section. Users now can add and delete annotations to the game trivia section.
> Add game trivia annotation functionality

- ludos/frontend/src/components/GameCard.js
I fixed the gamecard to prevent backend from being overwhelmed
> Remove unused state variables and useEffect in GameCard.js

- ludos/mobile/lib/change_password.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/game_reviews_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/login_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reusable_widgets/custom_navigation_bar.dart
- ludos/mobile/lib/thread_page.dart
- ludos/mobile/lib/userProvider.dart
- ludos/mobile/lib/user_profile_page.dart
Issue: 
#826 
Description:
We did some optimization in the app.
> BugFix: Reduced API Calls

- ludos/frontend/src/pages/GamesPage.js
Added if check for empty search key.
> bugfix search

- ludos/frontend/src/components/CreateThreadForm.js
- ludos/frontend/src/pages/CreateGroupPage.js
Bug is fixed in create thread and create group while choosing the game. Added an if check to setting search key.
> added if check to set search key

- ludos/mobile/lib/group/create_group.dart
- ludos/mobile/lib/group/group_summary.dart
- ludos/mobile/lib/group/groups.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/reusable_widgets/custom_navigation_bar.dart
- ludos/mobile/lib/reusable_widgets/game_summary.dart
- ludos/mobile/pubspec.lock
- ludos/mobile/pubspec.yaml
Issue: 
#768 
Description:
I revised and updated the look of tags in the game summary and the group summary.
> Tag Revision

- ludos/frontend/src/components/Header.js
- ludos/frontend/src/pages/GamePage.js
Add semantic search option and update data retrieval based on semantic flags. User can check the box if semantic search is used.
> Semantic Search

- ludos/frontend/src/components/CreateGameForum.js
As mentioned in the #728 , the route was not working, I added refreshing after navigating to solve problem.
> page refreshed after navigating

- .github/workflows/frontend-deploy.yml
We moved backend so our api is changed. I changed it in our actions pipeline.
> Changed backend request url

- ludos/frontend/src/components/ThreadComponent.js
There was a problem in request url so it was not displaying annotations on some images. It is resolved.
> image annotation bugfix

- ludos/mobile/lib/activation_for_password_reset.dart
- ludos/mobile/lib/forgot_password.dart
- ludos/mobile/lib/forum_page.dart
- ludos/mobile/lib/game_page.dart
- ludos/mobile/lib/games_page.dart
- ludos/mobile/lib/group/groups.dart
- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/login_page.dart
- ludos/mobile/lib/main.dart
- ludos/mobile/lib/reset_password.dart
- ludos/mobile/lib/reusable_widgets/custom_widgets.dart
- ludos/mobile/lib/reusable_widgets/forum_comment.dart
- ludos/mobile/lib/reusable_widgets/like_dislike_button.dart
- ludos/mobile/lib/search_game.dart
- ludos/mobile/lib/sign_up_page.dart
- ludos/mobile/lib/thread_page.dart
When the user logged out and press back button, it returns as logged in. In thread edit function, when the press back it shows edited fields again. These bugs fixed.
> bugfix-logout and edit thread page

- ludos/frontend/src/components/GameCard.js
- ludos/frontend/src/pages/GamesPage.js
I added detailed search feature to tha games page. user now can search with title, developer, tags, and sort by title, followers and id. User can also change order by descending or ascending
> Added detailed search to games page

- ludos/mobile/lib/reusable_widgets/forum_comment.dart
- ludos/mobile/lib/reusable_widgets/upcoming_title_post.dart
- ludos/mobile/lib/thread_page.dart
- ludos/mobile/lib/upcoming_title_thread_page.dart
Resolved merge conflicts in development.
> conflicts resolved

- ludos/mobile/lib/helper/APIService.dart
- ludos/mobile/lib/reusable_widgets/forum_comment.dart
Issue #851 
I implemented annotation for comments.
> Comment annotation added

- ludos/frontend/src/components/GroupTab.js
- ludos/frontend/src/pages/GamePage.js
Added group tab to the game page
> Added group tab to the game page

- ludos/mobile/lib/group/group_forum.dart
- ludos/mobile/lib/group/group_page.dart
- ludos/mobile/lib/group/group_summary.dart
- ludos/mobile/lib/group/groups.dart
> Final Fixes

- ludos/frontend/src/pages/ForumsPage.js
> Update ForumTopic import and usage

- ludos/frontend/src/components/CreateEntityForm.js
> Refactor handleDescriptionChange in CreateEntityForm.js

- ludos/frontend/src/components/EntityTab.js
* Fixed "area" bug which causes not to display environments.
> fixed entity tab bug
